### ISSUE TITLE
좋은 나쁨 기준 변경 법

### ISSUE THREAD

**Issue by ohnggni** [slasherLee/homebridge-airkorea#1]
안녕하세요? 만들어주신 plugin을 아주 잘 사용하고 있습니다.
최근 우리나라도 미세먼지 기준에 pm2.5기준을 도입한 것으로 알고 있습니다.
따라서 홈킷에 표시될 때도 초미세먼지 pm2.5기준으로 
0 ~ 15 좋음
16 ~ 35 보통
36 ~ 75 나쁨
76이상 매우나쁨

으로 표시하고 싶은데, 어떻게 수정하면 좋을지 도움부탁드립니다.

**Comment by slasherLee** [comment]
PM2.5 기준으로 변경을 하시려면 우선 아래의 코드
97번째 라인의 이 부분을 주석처리(//)하시고 참고하셔서 
that.conditions.air_quality = that.convertGrade(data.list[0].khaiValue);
114와 115번째 줄 사이에 
that.conditions.air_quality = that.convertGrade(data.list[0].pm25Value);
를 추가하시면 될꺼 같습니다. 

그리고 아래 172번째 줄의 소스의 숫자 부분을 아래와 같이 원하시는 수치로 고치시면 됩니다.
참고로 매우 좋음 위에 기준에 없으니 알아서 판단하셔야 할꺼 같습니다. (아래는 참고사항입니다.)
 convertGrade: function (grade) {
        var characteristic;
        if (!grade) {
            characteristic = Characteristic.AirQuality.UNKNOWN;
        } else if (grade >= 76) {
            characteristic = Characteristic.AirQuality.POOR;
        } else if (grade >= 36) {
            characteristic = Characteristic.AirQuality.INFERIOR;
        } else if (grade >= 16) {
            characteristic = Characteristic.AirQuality.FAIR;
        } else if (grade >= 1) {
            characteristic = Characteristic.AirQuality.GOOD;
        } else if (grade == 0) {
            characteristic = Characteristic.AirQuality.EXCELLENT;
        } else {
            characteristic = Characteristic.AirQuality.UNKNOWN;
        }
        return characteristic;
    },

참고로 PM2.5가 항상 갱신되지 않는 지역이시라면 표시되지 않는 경우가 있는 것을 감안하셔야 합니다.

**Comment by slasherLee** [comment]
PM2.5 기준으로 변경을 하시려면 우선 아래의 코드
97번째 라인의 이 부분을 주석처리(//)하시고 참고하셔서 
that.conditions.air_quality = that.convertGrade(data.list[0].khaiValue);
114와 115번째 줄 사이에 
that.conditions.air_quality = that.convertGrade(data.list[0].pm25Value);
를 추가하시면 될꺼 같습니다. 

그리고 아래 172번째 줄의 소스의 숫자 부분을 아래와 같이 원하시는 수치로 고치시면 됩니다.
참고로 매우 좋음 위에 기준에 없으니 알아서 판단하셔야 할꺼 같습니다. (아래는 참고사항입니다.)
 convertGrade: function (grade) {
        var characteristic;
        if (!grade) {
            characteristic = Characteristic.AirQuality.UNKNOWN;
        } else if (grade >= 76) {
            characteristic = Characteristic.AirQuality.POOR;
        } else if (grade >= 36) {
            characteristic = Characteristic.AirQuality.INFERIOR;
        } else if (grade >= 16) {
            characteristic = Characteristic.AirQuality.FAIR;
        } else if (grade >= 1) {
            characteristic = Characteristic.AirQuality.GOOD;
        } else if (grade == 0) {
            characteristic = Characteristic.AirQuality.EXCELLENT;
        } else {
            characteristic = Characteristic.AirQuality.UNKNOWN;
        }
        return characteristic;
    },

참고로 PM2.5가 항상 갱신되지 않는 지역이시라면 표시되지 않는 경우가 있는 것을 감안하셔야 합니다.

**Comment by ohnggni** [comment]
감사합니다. 잘 되네요~~^^
