### ISSUE TITLE
활성화 상태가 아니오로 표시됨

### ISSUE THREAD

**Issue by yungbang** [slasherLee/homebridge-airkorea#2]
안녕하세요, 만들어 주신 plugin은 매우 잘 사용하고 있습니다.

다만 홈 앱에서 활성화 상태가 아니오로 표시되는 문제가 있습니다.

index.js 내에 getData에서 문제가 없을 경우 아래 코드가 추가되어야 할 것 같습니다.

that.sensorService
    .getCharacteristic(Characteristic.StatusActive)
    .setValue(true);

감사합니다.

**Comment by slasherLee** [comment]
알려주셔서 감사합니다. 늦었지만 0.0.6에서 반영하였습니다.
