### ISSUE TITLE
선생님 잘쓰고있습니다. 문의사항 있어서 글남깁니다.

### ISSUE THREAD

**Issue by ddong3000** [slasherLee/homebridge-airkorea#3]
'Version ; 업데이트 날짜 및 시간' 을 반영코자 하는데 
제가 무지식인지라 json을 어떻게 수정하면 되는지 조언 좀 구합니다.
답변 부탁드립니다. 감사합니다.

**Comment by slasherLee** [comment]
제가 이걸 만든지가 오래되서 기억이 명확하지 않은데 잠깐 살펴보니 해당 내용을 별도로 구현해서 집어넣어야만 원하시는 값을 표시할 수 있을꺼 같습니다. 단순히 json 수정 만으로는 어려울꺼 같습니다.

**Comment by slasherLee** [comment]
> 'Version ; 업데이트 날짜 및 시간' 을 반영코자 하는데
> 제가 무지식인지라 json을 어떻게 수정하면 되는지 조언 좀 구합니다.
> 답변 부탁드립니다. 감사합니다.

**Comment by slasherLee** [comment]
> 'Version ; 업데이트 날짜 및 시간' 을 반영코자 하는데
> 제가 무지식인지라 json을 어떻게 수정하면 되는지 조언 좀 구합니다.
> 답변 부탁드립니다. 감사합니다.

**Comment by slasherLee** [comment]
제가 이걸 만든지가 오래되서 기억이 명확하지 않은데 잠깐 살펴보니 해당 내용을 별도로 구현해서 집어넣어야만 원하시는 값을 표시할 수 있을꺼 같습니다. 단순히 json 수정 만으로는 어려울꺼 같습니다.

**Comment by ddong3000** [comment]
헉 답변 감사합니다. 

}
                                if (data.list[0].dataTime != "-") {
                                    that.conditions.co = parseFloat(data.list[0].dataTime);
                                    that.log.debug('Current time is: %s', that.conditions.time);
                                    that.sensorService
                                        .getCharacteristic(Characteristic.time)
                                        .setValue(that.conditions.time); 
 }

이런식으로 CO level 밑에 붙여넣으면 time을 불러올 수 있지 않을까요?

**Comment by ddong3000** [comment]
아 안되네요...ㅠㅎㅎㅎ
혹시 부탁드려도 될련지요 ㅠㅠ

**Comment by slasherLee** [comment]
한군데만 고쳐서 될 문제가 아닐꺼 같습니다. 그리고 현재는 제가 저 환경을 사용하지 않아서 테스트도 어려울꺼 같네요. 도움을 못드려 죄송합니다.

**Comment by ddong3000** [comment]
아닙니다 덕분에 많은 사용자 분들이 이 플러그인 잘 쓰고 있습니다! 답변 감사드립니다!
