### ISSUE TITLE
url 변경 수정 도와주십시오

### ISSUE THREAD

**Issue by ddong3000** [slasherLee/homebridge-airkorea#4]
endpoint 주소가 변경됨에 따라 더이상 플러그인이 작동하지 않습니다.. 마지막으로 한번만 이부분 수정을 머리숙여 간곡히 부탁드립니다. 

기존 http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/

변경 
http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/

**Comment by slasherLee** [comment]
요청하신대로 변경된 url로 수정하였습니다. 하지만 제가 테스트 환경을 갖고 있지 않아 테스트 부탁드립니다.

**Comment by ddong3000** [comment]
> 요청하신대로 변경된 url로 수정하였습니다. 하지만 제가 테스트 환경을 갖고 있지 않아 테스트 부탁드립니다.

안되네요 에러 503 뿜고있어요 기존 url로 요청하는거같아요

**Comment by ddong3000** [comment]
> > 요청하신대로 변경된 url로 수정하였습니다. 하지만 제가 테스트 환경을 갖고 있지 않아 테스트 부탁드립니다.
> 
> 안되네요 에러 503 뿜고있어요 기존 url로 요청하는거같아요

json return값도 변동이 있어 코드 수정이 필요해 보입니다 너무 아쉽네요 이제 못쓰게 되서ㅠㅠ

**Comment by slasherLee** [comment]
안그래도 변경 사항이 url 한가지가 아닌거 같더라구요. 우선 제가 환경을 구축해서 보려고 하는데 시간이 조금 필요할 듯 싶습니다.

**Comment by ddong3000** [comment]
> 안그래도 변경 사항이 url 한가지가 아닌거 같더라구요. 우선 제가 환경을 구축해서 보려고 하는데 시간이 조금 필요할 듯 싶습니다.

꼭 기다리겠습니다.. 후원 필요하시면 후원도 해드리겠습니다 그만큼 정말 애정있게 쓴 플러그인입니다 정말 감사합니다 🙇🏻‍♂️

**Comment by slasherLee** [comment]
제가 수정 후 테스트 완료 하였습니다. 전에 요청하셨던 업데이트 타임도 반영하려 했으나 실시간으로 업데이트 되는 값이 다 숫자밖에 없어서 넣을 공간이 없네요. 그 외 결과는 다 전처럼 잘 나오는 것을 확인 하였습니다.

**Comment by ddong3000** [comment]
> 제가 수정 후 테스트 완료 하였습니다. 전에 요청하셨던 업데이트 타임도 반영하려 했으나 실시간으로 업데이트 되는 값이 다 숫자밖에 없어서 넣을 공간이 없네요. 그 외 결과는 다 전처럼 잘 나오는 것을 확인 하였습니다.

NPM업뎃하신 후에 다시 설치하면 될까요?

**Comment by slasherLee** [comment]
npm을 통한 설치 명령어를 다시 입력하시면 업데이트 됩니다. 참고로 버젼은 0.0.6입니다.

**Comment by ddong3000** [comment]
설치시 에러 송출됩니다ㅜㅜ

**Comment by ddong3000** [comment]
![Uploading CB084ABC-C0AC-4077-AFBF-B843415BC071.png…]()

**Comment by ddong3000** [comment]
> npm을 통한 설치 명령어를 다시 입력하시면 업데이트 됩니다. 참고로 버젼은 0.0.6입니다.

![Uploading 04E91021-2218-4076-BBD0-EB3127B3D55B.png…]()
![CB06D278-E043-4EED-AC1F-3566F5B38284](https://user-images.githubusercontent.com/54649785/119788850-78607700-bf0d-11eb-9a1e-c6ad2dd70366.png)

이런 에러메시지 송출됩니다 어떻게 해야하나요?

**Comment by slasherLee** [comment]
앞에 sudo를 치셔야 합니다. sudo npm -g install ..... 이런식으로요

**Comment by ddong3000** [comment]
> 앞에 sudo를 치셔야 합니다. sudo npm -g install ..... 이런식으로요

알겠습니다

**Comment by ddong3000** [comment]
> > 앞에 sudo를 치셔야 합니다. sudo npm -g install ..... 이런식으로요
> 
> 알겠습니다

![7CA68542-0E08-4323-9AC0-3A4CA8D1E975](https://user-images.githubusercontent.com/54649785/119790786-2ae50980-bf0f-11eb-943c-83692cf6bcee.jpeg)

sudo 권한으로 해도 에러 뜨네요ㅜㅜㅜ 어떻게 해야하죠 자꾸 귀찮게 해드려서 죄송합니다

**Comment by slasherLee** [comment]
작업 폴더에 git clone https://github.com/slasherLee/homebridge-airkorea 명령으로 소스를 다운 받으셔서 sudo npm -g install ./homebridge-airkorea로 설치해보시기 바랍니다

**Comment by ddong3000** [comment]
> 작업 폴더에 git clone https://github.com/slasherLee/homebridge-airkorea 명령으로 소스를 다운 받으셔서 sudo npm -g install ./homebridge-airkorea로 설치해보시기 바랍니다

알겠습니다 복잡하네요ㅜㅜ 꼭 성공해보겠습니다 도와주셔서 정말 감사드립니다

**Comment by ddong3000** [comment]
> > 작업 폴더에 git clone https://github.com/slasherLee/homebridge-airkorea 명령으로 소스를 다운 받으셔서 sudo npm -g install ./homebridge-airkorea로 설치해보시기 바랍니다
> 
> 알겠습니다 복잡하네요ㅜㅜ 꼭 성공해보겠습니다 도와주셔서 정말 감사드립니다

제가 git clone 하는법이 생소합니다.. 혹시 라즈베리 내에 있는 index.js와 package.json 내용을 그대로 복붙해서 사용이 가능한지 여쭤봅니다
![7AD72E20-0DC8-4F59-B463-B5DD9061336A](https://user-images.githubusercontent.com/54649785/119803476-7355f480-bf1a-11eb-97bd-14aa18c8e99f.jpeg)

**Comment by ddong3000** [comment]
> 작업 폴더에 git clone https://github.com/slasherLee/homebridge-airkorea 명령으로 소스를 다운 받으셔서 sudo npm -g install ./homebridge-airkorea로 설치해보시기 바랍니다

어찌어찌해서 0.0.6으로 업뎃 완료했습니다!!
그런데 pm2.5가 안올라오네요 이부분은 어떻게 하면 좋을까요?

**Comment by ddong3000** [comment]
> > 작업 폴더에 git clone https://github.com/slasherLee/homebridge-airkorea 명령으로 소스를 다운 받으셔서 sudo npm -g install ./homebridge-airkorea로 설치해보시기 바랍니다
> 
> 어찌어찌해서 0.0.6으로 업뎃 완료했습니다!!
> 그런데 pm2.5가 안올라오네요 이부분은 어떻게 하면 좋을까요?

Characteristic PM2_5Density 이슈가 있는 것 같습니다 다른 데이터는 잘 올라옵니다 확인 부탁드립니다

https://github.com/homebridge/HAP-NodeJS/issues/532

**Comment by slasherLee** [comment]
아마 지금 측정하고 계신 측정소가 pm25를 지원하지 않아서 일꺼 같습니다. 전에는 지원안하는 곳이 0으로 표시되었는데 현재는 아예
표시 안되도록 수정하였습니다.

2021년 5월 28일 (금) 오전 6:32, ddong3000 ***@***.***>님이 작성:

**Comment by ddong3000** [comment]
> 아마 지금 측정하고 계신 측정소가 pm25를 지원하지 않아서 일꺼 같습니다. 전에는 지원안하는 곳이 0으로 표시되었는데 현재는 아예 표시 안되도록 수정하였습니다. 2021년 5월 28일 (금) 오전 6:32, ddong3000 ***@***.***>님이 작성:
> […](#)

![13BDC78D-E0D1-4776-8E57-180B9A1869F7](https://user-images.githubusercontent.com/54649785/119911070-9bce0500-bf93-11eb-9509-c9fd5a272652.jpeg) 
저의 측정소는 보시다시피 pm25 지원 측정소입니다 코드 수정전에도 pm10과 pm2.5 둘다 수신이 잘 되엇거든요 너무 귀찮게 해드리는 것 같아 죄송스럽습니다

pm25grade 값때문에 value값이 안올라오는건지 참 이상하네요

**Comment by ddong3000** [comment]
> > 아마 지금 측정하고 계신 측정소가 pm25를 지원하지 않아서 일꺼 같습니다. 전에는 지원안하는 곳이 0으로 표시되었는데 현재는 아예 표시 안되도록 수정하였습니다. 2021년 5월 28일 (금) 오전 6:32, ddong3000 _**@**_.***>님이 작성:
> > […](#)
> 
> ![13BDC78D-E0D1-4776-8E57-180B9A1869F7](https://user-images.githubusercontent.com/54649785/119911070-9bce0500-bf93-11eb-9509-c9fd5a272652.jpeg)
> 저의 측정소는 보시다시피 pm25 지원 측정소입니다 코드 수정전에도 pm10과 pm2.5 둘다 수신이 잘 되엇거든요 너무 귀찮게 해드리는 것 같아 죄송스럽습니다
> 
> pm25grade 값때문에 value값이 안올라오는건지 참 이상하네요

![D8488C63-4362-48B4-8221-6E1D48F37B4C](https://user-images.githubusercontent.com/54649785/119911551-7261a900-bf94-11eb-8704-0d8f20942a72.png)

**Comment by slasherLee** [comment]
사용하시는 측정소 이름을 알려주실수 있을까요? 제가 몇군데 찾아봤는데 pm25 나오는 것이 잘 없어서요.

**Comment by ddong3000** [comment]
> 사용하시는 측정소 이름을 알려주실수 있을까요? 제가 몇군데 찾아봤는데 pm25 나오는 것이 잘 없어서요.

한강신도시 입니다. 부탁드립니다

**Comment by slasherLee** [comment]
기존에 url에 ver을 안넣어도 pm2.5가 나왔던거 같은데 현재는 추가하지 않으면 나오지 않는군요. 추가해서 업데이트 하였습니다.

**Comment by ddong3000** [comment]
> 기존에 url에 ver을 안넣어도 pm2.5가 나왔던거 같은데 현재는 추가하지 않으면 나오지 않는군요. 추가해서 업데이트 하였습니다.
 
감사합니다 바로 업뎃하고 피드백하겠습니다

**Comment by ddong3000** [comment]
> 기존에 url에 ver을 안넣어도 pm2.5가 나왔던거 같은데 현재는 추가하지 않으면 나오지 않는군요. 추가해서 업데이트 하였습니다.

![4E330B85-D9AF-470D-A1E6-36C83B3B9B37](https://user-images.githubusercontent.com/54649785/119918283-1baf9b80-bfa3-11eb-9787-2b83909edbbb.png)
완벽한 에어코리아 플러그인으로 재탄생하였습니다
개발자 선생님의 큰 노고 고개숙여 깊이 감사를 드립니다 항상 응원하겠습니다 다시 한번 정말 감사합니다🙆🏻‍♂️
